# See https://pre-commit.com/ for more information
exclude: _pb2\.py$

repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.11.32 # Use the latest available version
    hooks:
      - id: uv-lock

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.0
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-json
        exclude: ^\.vscode/launch\.json$
      - id: check-merge-conflict
        args: [--assume-in-merge]
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.16
    hooks:
      - id: vulture
        args: ["pymal", "--min-confidence", "80"]

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.38.0
    hooks:
      - id: yamllint
