[build-system]
requires = ["uv_build>=0.11.2,<0.12"]
build-backend = "uv_build"

[project]
name = "pymal"
version = "1.0.0"
requires-python = "<3.15,>=3.10"
description = "A python api for the website MyAnimeList (or MAL)."
authors = []
dependencies = [
    "niquests[socks,utls]<4.0.0,>=3.13.1",
    "beautifulsoup4<5.0.0,>=4.12.3",
    "lxml<7.0.0,>=6.0.0",
    "pillow>=12.3.0",
    "singleton-factory>=0.1",
]

[tool.uv]
default-groups = "all"
package = true

[tool.uv.build-backend]
module-root = "."
module-name = "pymal"

[dependency-groups]
dev = [
    "ruff<1.0.0,>=0.11.0",
    "coveralls>=0.4.2",
    "mock==1.0.1",
    "pytest>=9.1.1",
]

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B", "A", "C4", "T20", "SIM", "ARG", "PTH"]
ignore = ["E501"]
unfixable = ["B"]

[tool.ruff.lint.isort]
lines-after-imports = 2

[tool.ruff]
exclude = [
    ".bzr", ".direnv", ".eggs", ".git", ".hg",
    ".mypy_cache", ".nox", ".pytest_cache", ".ruff_cache",
    ".svn", ".tox", ".venv", "__pypackages__",
    "_build", "buck-out", "build", "dist",
    "node_modules", "site-packages", "venv",
]
line-length = 90
indent-width = 4
target-version = "py311"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[[tool.mypy.overrides]]
ignore_errors = true
ignore_missing_imports = true
